name: CI

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5.0.0
      with:
        cache-dependency-path: go.sum
        go-version-file: go.mod

    - name: Test
      run: make -f builder.Makefile test
