name: ECS integration tests

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  ecs-tests:
    name: ECS e2e tests

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5.0.0
      with:
        cache-dependency-path: go.sum
        go-version-file: go.mod

    - name: Build for ECS e2e tests
      run: make -f builder.Makefile cli

    - name: create aws config folder
      run: mkdir -p ~/.aws

    - name: ECS e2e Test
      env:
        AWS_DEFAULT_REGION: us-east-1
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      run: make e2e-ecs
